import { Button, VerticalBox } from "std-widgets.slint";
import { ChessBoard } from "chessboard.slint";

export struct TranslationArgument {
    name: string,
    value: string,
}

export global Translator {
    pure callback translate(string, [TranslationArgument]) -> string;
}

export component AppWindow inherits Window {
    protected pure function tr(str: string, args: [TranslationArgument]) -> string {
        return Translator.translate(str, args);
    }
    width: 900px;
    height: 900px;
    in property pieces <=> board.pieces;
    in property whiteTurn <=> board.whiteTurn;

    board:= ChessBoard {
        size: 500px;
        reversed: true;
        whiteTurn: false;
    }
}
