import { Button, VerticalBox } from "std-widgets.slint";
import { ChessBoard } from "chessboard.slint";

export struct TranslationArgument {
    name: string,
    value: string,
}

export global Translator {
    pure callback translate(string, [TranslationArgument]) -> string;
}

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    callback request-increase-value();
    protected pure function tr(str: string, args: [TranslationArgument]) -> string {
        return Translator.translate(str, args);
    }
    width: 900px;
    height: 900px;
    /*
    VerticalBox {
        Text {
            text: root.tr("counter", [{name: "counter", value: root.counter}]);
        }
        Button {
            text: root.tr("increase-button", []);
            clicked => {
                root.request-increase-value();
            }
        }
    }
    */
    ChessBoard {
        size: 150px;
        reversed: true;
    }
}
