export component ChessBoard {
    in property <length> size;
    in property <color> backgroundColor: cadetblue;
    in property <color> whiteCellColor: navajowhite;
    in property <color> blackCellColor: peru;
    in property <color> coordinatesColor: maroon;
    in property <bool> reversed: false;
    in property <bool> whiteTurn: true;

    Rectangle {
        width: size;
        height: size;
        background: backgroundColor;

            for row in 8 : Rectangle {
                width: size;
                height: size / 9;
                x: 0;
                y: (size / 9) * (row+0.5);
                for col in 8 : Rectangle {
                    width: size / 9;
                    height: size / 9;
                    x: (size / 9) * (col+0.5);
                    background: mod(row+col, 2) == 0 ? whiteCellColor : blackCellColor;
                }
            }

            for file in 8: Text {
                x: (size/9) * (0.9 + (reversed ? (7-file) : file));
                y: (size/9) * 0.05;
                color: coordinatesColor;
                font-weight: 200;
                font-size: (size/27);
                text: ["A", "B", "C", "D", "E", "F", "G", "H"][file];
            }

            for file in 8: Text {
                x: (size/9) * (0.9 + (reversed ? (7-file) : file));
                y: (size/9) * 8.55;
                color: coordinatesColor;
                font-weight: 200;
                font-size: (size/27);
                text: ["A", "B", "C", "D", "E", "F", "G", "H"][file];
            }

            for rank in 8: Text {
                x: (size/9) * 0.15;
                y: (size/9) * (0.85 + (reversed ? rank : (7-rank)));
                color: coordinatesColor;
                font-weight: 200;
                font-size: (size/27);
                text: ["1", "2", "3", "4", "5", "6", "7", "8"][rank];
            }

            for rank in 8: Text {
                x: (size/9) * 8.65;
                y: (size/9) * (0.85 + (reversed ? rank : (7-rank)));
                color: coordinatesColor;
                font-weight: 200;
                font-size: (size/27);
                text: ["1", "2", "3", "4", "5", "6", "7", "8"][rank];
            }
            
            Rectangle {
                border-radius: size/36;
                x: (size/9) * 8.5;
                y: (size/9) * 8.5;
                width: size/18;
                height: size/18;
                background: whiteTurn? white : black;
            }
    }
}